server:
  port: 8082
grpc:
  client:
    hello:
      address: localhost:9090
      negotiation-type: plaintext

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level [%t] [%logger - %line]: %m%n"
  level:
    com.rga.demogrpcconsumer: info
  include-application-name: false