server:
  port: 8081
grpc:
  server:
    port: 9090
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level [%t] [%logger - %line]: %m%n"
  level:
    com.rga.demogrpcprovider: info
  include-application-name: false